# Web server properties start with prefix 'server'
server:
  port: 8080

#You must enable AND expose actuator endpoints
# Spring Boot 2 requires enabling and exposing
management:
  endpoints:
    enabled-by-default: true  #enable all
    web:
      exposure:
        include:
          - '*'               #expose all

# Example of custom config property handling
example:
  string-one: The first
  string-two: 2nd
  email: backup@email.com
  my-number: 8849
  map:
    z: Thing Z
    y: Thing Y
    x: Thing X

spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect


# Example of how to configure endpoints individually
#management:
#  endpoint:
#    auditevents:
#      enabled: true
#    beans:
#      enabled: true
#    conditions:
#      enabled: true
#    health:
#      enabled: true
#    info:
#      enabled: true
#  endpoints:
#    web:
#      exposure:
#        include:
#          - auditevents
#          - beans
#          - conditions
#          - health
#          - info

# Change actuator web path from `actuator` to `manage`
#management:
#  endpoints:
#    web.base:
#      path: '/manage'
